# Generated by Django 4.2.7 on 2024-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_address_purchase_purchaseitem_purchase_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
