# Generated by Django 4.2.7 on 2024-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_purchase_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_id',
            field=models.TextField(),
        ),
    ]
