# Generated by Django 4.2.7 on 2024-03-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
            preserve_default=False,
        ),
    ]
